apiVersion: v1
clusters:
- cluster:
    server: http://127.0.0.1:20888
  name: local
contexts:
- context:
    cluster: local
    user: local
  name: local
current-context: local
kind: Config
users:
- name: local